### ISSUE TITLE
iOS 7 - Safari - game has stopped working

### ISSUE THREAD

**Issue by avstudios** [bp74/StageXL#46]
Hi Bernhard,

My game is not working on the iPad (iOS 7.0.2). I've debugged it and there is an error:
NoSuchMethodError: Cannot call "mH" ('undefined' is not a function (evaluating 'J.RE(a).mH(a)'))

I know there are many issues on iOS 7 at the moment. But I'm wandering if it comes from dart itself. Thanks for any help.
